twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        languages: '@App\Generator\LanguageGenerator'

when@test:
    twig:
        strict_variables: true
